### ISSUE TITLE
Changing the account is tedious because the account change popup is closed upon a balance update

### ISSUE THREAD

**Issue by clangenb** [integritee-network/try-incognitee-app#84]
Reproduce:

1. Log in with an account
2. Wait until the account change pop up is closed
3. Try to change the account again
4. wait for 2ish seconds -> popup automatically closes again (too fast to properly select an account)

**Comment by clangenb** [comment]
Hmm, weird. It seems the app can be brought into a state where the above bug doesn't happen.

**Comment by clangenb** [comment]
It might be that opening he `ChooseWalletOverlay` causes this.

**Comment by brenzi** [comment]
I'll close this now as #85 is solved. please reopen if it still happens

**Comment by clangenb** [comment]
Intuitively, it doesn't make sense that it was fixed #85, but I can confirm that it is solved now.
